import type { Metadata } from "next"
import "./globals.css"
import Providers from "@/components/provider/Providers"
import ProgressBar from "@/components/ProgressBar"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const RootLayout = (props: { children: React.ReactNode }) => {
    return (
        <Providers>
            <html lang="en">
                <body className="bg-stone-200 h-screen w-full py-16">
                    <ProgressBar />
                    <div className="max-w-[1000px] mx-auto h-full">
                        {props.children}
                    </div>
                </body>
            </html>
        </Providers>
    )
}

export default RootLayout
